config/routes.rb
Rails.application.routes.draw do
  devise_for :supporters
  root to: 'supporters#new' 

  get "/pages/:page" => "pages#show"

  namespace :admin do
    get '/map', to: 'pages#map', as: :map
    resources :publicities
    # resources :supporters, only: :index
  end

  localized do
    resources :greendays
    get '/initiative_text', to: 'pages#show', as: :initiative_text, page: 'initiative_text'
    get '/arguments', to: 'pages#show', as: :arguments, page: 'arguments'
    get '/faq', to: 'pages#show', as: :faq, page: 'faq'
    get '/terms_and_conditions', to: 'pages#show', as: :terms_and_conditions, page: 'terms_and_conditions'
    get '/sponsoring', to: 'pages#show', as: :sponsoring, page: 'sponsoring'
    get '/donation', to: 'pages#show', as: :donation, page: 'donation'
    get '/numbers', to: 'pages#show', as: :numbers, page: 'numbers'
    get '/collection_concept', to: 'pages#show', as: :collection_concept, page: 'collection_concept'
    get '/statements', to: 'pages#show', as: :statements, page: 'statements'
  end

  get '/cities_autocomplete', to: 'cities_autocomplete#index', as: :cities_autocomplete
  scope '/:locale',  locale: /de|it|fr/ do
    get '/', to: 'supporters#new'
    resources :supporters, only: [:new, :create]
    resource :publicity
    get '/thanks', to: 'pages#thanks', as: :thanks
    resources :charges    
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/models/greenday.rb
class Greenday
  include Mongoid::Document
  include Mongoid::Timestamps
  include Geocoder::Model::Mongoid
  include Mongoid::Paperclip

  before_save :delete_logo?

  has_mongoid_attached_file :logo,
                            path: ':attachment/:id/:style.:extension',
                            styles: {
                              original: ['1920x1680>', :jpg],
                              small:    ['100x100#',   :jpg],
                              medium:   ['250x250',    :jpg],
                              large:    ['500x500>',   :jpg]
                            },
                            convert_options: { all: '-background white -flatten +matte' }

  field :title, type: String
  field :address, type: String
  field :homepage, type: String
  field :description, type: String
  field :coordinates, type: Array

  geocoded_by :address
  after_validation :geocode # auto-fetch coordinates

  validates :title, presence: true
  validates :address, presence: true
  validates_attachment_content_type :logo, content_type: ['image/jpg', 'image/jpeg', 'image/png', 'image/gif']

  def delete_logo
    @delete_logo ||= '0'
  end

  attr_writer :delete_logo

  private

  def delete_logo?
    logo.clear if @delete_logo == '1'
  end
end

app/controllers/greendays_controller.rb
class GreendaysController < ApplicationController
  before_action :only_admin, except: [:index, :show]
  before_action :set_greenday, only: [:show, :edit, :update, :destroy]

  def index
    @greendays = Greenday.all.sort(title: 1)
  end

  def new
    @greenday = Greenday.new
  end

  def edit; end

  def create
    @greenday = Greenday.new(greenday_params)

    respond_to do |format|
      if @greenday.save
        format.html { redirect_to greendays_path, success: 'Greenday was successfully created.' }
        format.json { render :show, status: :created, location: @greenday }
      else
        format.html { render :new }
        format.json { render json: @greenday.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @greenday.update(greenday_params)
        format.html { redirect_to greendays_path, notice: 'Greenday was successfully updated.' }
        format.json { render :show, status: :ok, location: @greenday }
      else
        format.html { render :edit }
        format.json { render json: @greenday.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @greenday.destroy
    respond_to do |format|
      format.html { redirect_to greendays_path, notice: 'Greenday was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_greenday
    @greenday = Greenday.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def greenday_params
    params.require(:greenday).permit(:title, :address, :homepage, :description, :logo, :delete_logo)
  end

  def only_admin
    return true if current_supporter && current_supporter.admin?
    raise ActionController::RoutingError, 'Not Found'
  end
end

app/views/greendays/_description.de.slim
b Am Samstag 25. November ist Nationaler CBD-Tag!
p Um die #{link_to 'Finanzierung der Sammlung und Beglaubigung', donation_path} der eidgenössischen #{link_to 'Volksinitiative zur Cannabislegalisierung', initiative_text_path} in der Schweiz voranzutreiben, lanciert der Verein Legalize it! in Zusammenarbeit mit dem #{link_to 'Branchenverband IG Hanf', 'https://www.ighanf.ch/D_about.html', target: '_blank'} am Samstag 25. November 2017 den ersten nationalen CBD-Tag.
p In jedem Laden steht eine Spendenbox, welche für Spenden für die Initiative benutzt werden kann und die dem Verein Legalize it! zugute kommt.
p Welche Läden mitmachen, seht ihr auf der Karte:

app/views/greendays/_form.html.slim
= simple_form_for(@greenday) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :address, as: :text
    = f.input :homepage
    = f.input :description, as: :text
    = f.input :logo, as: :file, required: false
    = image_tag f.object.logo.url(:original), alt: '', class: 'img-responsive'
    = f.input :delete_logo, as: :boolean

  .form-actions
    = f.button :submit, 'Shop speichern'

app/views/greendays/edit.html.slim
h1 Editing greenday

== render 'form'

= link_to 'Show', @greenday
'  |
= link_to 'Back', greendays_path

app/views/greendays/index.html.slim
h1.sr-only = title '#Greensaturday'
= render 'description'
#map
= link_to 'Neuen Shop erfassen', new_greenday_path if admin?

.row.fix
  - @greendays.each do |greenday|
    .col-xs-12.col-sm-6.col-lg-4
      .well
        h2 = greenday.title
        - if greenday.logo.url(:original) != '/logos/original/missing.png'
          = image_tag greenday.logo.url(:original), alt: '', class: 'img-responsive'
        address = simple_format(greenday.address)
        - if greenday.homepage
          = link_to("Website", greenday.homepage, target: "_blank")
        p = markdown(greenday.description).html_safe

        - if admin?
          = link_to 'Bearbeiten', edit_greenday_path(greenday)
          | &nbsp;
          = link_to 'Löschen', greenday, data: { confirm: 'Are you sure?' }, method: :delete

javascript:
  function initMap() {

    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 8, center: {lat: 47.242, lng: 8.133},
    });

    var greendays_url = "#{greendays_url(format: :json)}"

    var infowindow = new google.maps.InfoWindow({
          content: '',
          maxWidth: 200
        });


    $.getJSON(greendays_url, function(json) {
      $.each(json, function(key, data) {
        var marker = new google.maps.Marker({
          position: {lat: data.coordinates[1], lng: data.coordinates[0] },
          map: map,
          title: data.title
        });

        marker.addListener('click', function() {
          infowindow.open(map, marker);

          var content = '<b>' + data.title + '</b>'
          if(data.logo) {
            content += '<img src="' + data.logo + ' alt="" width="100%"/>'
          }
          content += '<address>' + data.address.replace(/\n/g,"<br>")
          if(data.homepage) {
            content += '<br/><a href="' + data.homepage + '" target="_blank">Website</a>'
          }
          content += '</address>'

          if(data.description) {
            content += '<p>' + data.description + '</p>'
          }
          infowindow.setContent(content);
        });
      });
    });
  }

script async="" defer="" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBbwMtGKDqf4i8x9-OVP1-H_QVAKp92h2M&callback=initMap&libraries=visualization" 

app/views/greendays/new.html.slim
h1 New greenday

== render 'form'

= link_to 'Back', greendays_path