config/routes.rb
Rails.application.routes.draw do
  devise_for :supporters
  root to: 'supporters#new' 

  get "/pages/:page" => "pages#show"

  namespace :admin do
    get '/map', to: 'pages#map', as: :map
    resources :publicities
    # resources :supporters, only: :index
  end

  localized do
    resources :greendays
    get '/initiative_text', to: 'pages#show', as: :initiative_text, page: 'initiative_text'
    get '/arguments', to: 'pages#show', as: :arguments, page: 'arguments'
    get '/faq', to: 'pages#show', as: :faq, page: 'faq'
    get '/terms_and_conditions', to: 'pages#show', as: :terms_and_conditions, page: 'terms_and_conditions'
    get '/sponsoring', to: 'pages#show', as: :sponsoring, page: 'sponsoring'
    get '/donation', to: 'pages#show', as: :donation, page: 'donation'
    get '/numbers', to: 'pages#show', as: :numbers, page: 'numbers'
    get '/collection_concept', to: 'pages#show', as: :collection_concept, page: 'collection_concept'
    get '/statements', to: 'pages#show', as: :statements, page: 'statements'
  end

  get '/cities_autocomplete', to: 'cities_autocomplete#index', as: :cities_autocomplete
  scope '/:locale',  locale: /de|it|fr/ do
    get '/', to: 'supporters#new'
    resources :supporters, only: [:new, :create]
    resource :publicity
    get '/thanks', to: 'pages#thanks', as: :thanks
    resources :charges    
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/models/supporter.rb
class Supporter
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paranoia
  include Geocoder::Model::Mongoid

  COUNTER_START = 10_003

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ''
  field :encrypted_password, type: String, default: ''
  field :admin,              type: Boolean, default: false

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  geocoded_by :address
  after_validation :geocode          # auto-fetch coordinates

  field :first_name,    type: String
  field :last_name,     type: String
  field :street,        type: String
  field :zip,           type: Integer
  field :city,          type: String
  field :support,       type: String # Indicates the type of support
  field :li_membership, type: Boolean, default: false
  field :age_category,  type: String
  field :coordinates,   type: Array
  field :comments,      type: String
  field :language,      type: String
  field :duplicate,     type: Boolean, default: false
  field :tel,           type: String

  validates :first_name,   presence: true
  validates :last_name,    presence: true
  validates :street,       presence: true
  validates :zip,          presence: true
  validates :city,         presence: true
  validates :email,        presence: true, uniqueness: true, format: /.+@.+\..+/i
  validates :support,      presence: true
  validates :age_category, presence: true
  validates :language,     presence: true

  embeds_one :publicity

  def self.counter
    actual = count.to_i
    actual > COUNTER_START ? actual : COUNTER_START
  end

  def address
    "#{street}, #{zip}, #{city}, Switzerland"
  end
end

app/controllers/supporters_controller.rb
class SupportersController < ApplicationController
  before_filter :set_form_timestamp, only: :new

  def new
    @supporter = Supporter.new
  end

  def create
    @supporter = Supporter.new supporter_form_params.merge(language: I18n.locale)
    @supporter.password = random_password = SecureRandom.hex(5)
    if !input_to_fast? && @supporter.save
      SupporterMailer.welcome_email(@supporter, random_password).deliver_now
      sendy_registraion
      redirect_to thanks_path
    else
      flash.now[:danger] = input_to_fast? ? t('.timeout') : t('input_error')
      render :new
    end
  end

  private

  def supporter_form_params
    params.require(:supporter).permit(:first_name, :last_name, :street, :zip, :email, :support, :li_membership, :age_category, :city, :comments, :tel)
  end

  # We use sendy for newsletters atm
  def sendy_registraion
    uri = URI('http://newsletter.cannabis-initiative.ch/subscribe')
    Net::HTTP.post_form(uri, list: ENV["SENDY_LIST_#{I18n.locale.upcase}"],
                             email: @supporter.email,
                             name: "#{@supporter.first_name} #{@supporter.last_name}")
  end
end

app/views/supporters/_form.slim
- title(t('shared.header.title_html'))
.row
  .col-xs-12.col-md-7
    h2.sr-only = t('.form')
    = simple_form_for @supporter do |f|
      = f.input :first_name, placeholder: t('.placeholders.first_name')
      = f.input :last_name, placeholder: t('.placeholders.last_name')
      = f.input :street, placeholder: t('.placeholders.street')
      = f.input :city, placeholder: t('.placeholders.city')
      = f.input :zip, placeholder: t('.placeholders.zip')
      = f.input :email, placeholder: t('.placeholders.email')
      = f.input :tel, placeholder: '+41 (0) xxxx'
      = f.input :support, as: :radio_buttons, collection: t('support_type').map{ |x| [x.first, raw(x.last)]}, label_method: :last, value_method: :first
      = f.input :li_membership, as: :boolean
      = f.input :age_category, as: :radio_buttons, collection: t('age_category'), label_method: :last, value_method: :first
      = f.input :comments, as: :text
      .form-group
        = f.submit value: t('.submit'), class: 'btn btn-success'
      .form-group
        = link_to t('.terms_and_conditions'), terms_and_conditions_path, class: 'small'


    javascript:
      var cities = new Bloodhound({
        datumTokenizer: Bloodhound.tokenizers.whitespace,
        queryTokenizer: Bloodhound.tokenizers.whitespace,
        remote: {
          url: '/cities_autocomplete.json?query=%QUERY',
          wildcard: '%QUERY',
        }
      });
      
      var suggestion_template = function (data) {
          return '<p>' + data.plz + ' - ' + data.city + '</p>';
      }
      
      $('#supporter_city').typeahead({
        minLength: 2,
      },{
      limit: 20,
      display: 'city',
      templates: {
        suggestion: function (data) {
            return suggestion_template(data);
        }
      },
        source: cities 
      }).on('typeahead:selected', function(event, datum) {
        $("#supporter_zip").val(datum.plz);
      });
        
      $('#supporter_zip').typeahead({
        minLength: 2,
      },{
        limit: 20,
        display: 'plz',
        templates: {
          suggestion: function (data) {
              return suggestion_template(data);
          }
        },
        source: cities 
      }).on('typeahead:selected', function(event, datum) {
        $("#supporter_city").val(datum.city);
      });  
  aside.col-md-5.col-xs-12
    = render 'right_side'

app/views/supporters/_publicity.slim
- if current_supporter.publicity
  .panel.panel-default
    .panel-heading
      h2.panel-title 
        = t '.title'
    .panel-body 
       dl.dl-horizontal
        dt = Publicity.human_attribute_name(:status)
        dd= t("publicity_states.#{current_supporter.publicity.state}") 
        - unless current_supporter.publicity.organisation.blank?
          dt = Publicity.human_attribute_name(:organisation)
          dd = current_supporter.publicity.organisation
        dt = Publicity.human_attribute_name(:statement)
        dd = current_supporter.publicity.statement
        dt = Publicity.human_attribute_name(:avatar)
        dd = image_tag current_supporter.publicity.avatar.url(:small), alt: ''
       
       .pull-right
        = link_to t(".renew"), new_publicity_path
        br
        = link_to t(".delete"), publicity_path, data: { confirm: t("shared.are_you_sure") }, method: :delete, class: 'text-danger'
       
- else
  .alert.alert-notice 
    = link_to t('.create_publicity'), new_publicity_path

app/views/supporters/_right_side.de.slim
p
  = link_to 'https://marryjane.ch/de/product/legalize-it-indoor/', target: '_blank' do
    = image_tag 'gruene_hilfe_button.png', class: 'img-responsive', alt: 'Jetzt die Initiative mit einem Initiativsäckli unterstützen!'

.well
  h2.sr-only Über die Initiative
  p = image_tag 'li_logo.svg', class: 'img-responsive', alt: 'Logo des Vereins Legalize it!'
  p Wir wollen die nötigen Unterschriften für eine Volksinitiative zur Cannabis-Legalisierung sammeln. Für die Umsetzung setzt man auf ein neues Sammelkonzept. Dies funktioniert in drei Schritten:

  p
    strong Schritt 1:
    | Durch dieses Onlineformular sammeln wir Sympathisanten und potentielle Aktivisten.
  p
    strong Schritt 2:
    | Sobald die geforderte Anzahl Personen gesammelt sind, schauen wir, wie viele Ressourcen an Helfer/innen an welchen Orten benötigt werden.
  p
    strong Schritt 3:
    | Durch eine ausgeklügelte Logistik werden Sympathisanten und Aktivisten zusammengebracht, um gemeinsam die nötigen Unterschriften zu generieren.

  p.lead Wenn du also <span class="text-success">Cannabis in der Schweiz legalisieren</span> willst, fülle das nebenstehende Formular aus und schreibe mit uns Geschichte.

  / p.embed-responsive.embed-responsive-4by3
    iframe.embed-responsive-item src="https://www.youtube.com/embed/l5DjuLXRVVM" frameborder="0" allowfullscreen=""
  / p.embed-responsive.embed-responsive-4by3
    iframe src="https://www.youtube.com/embed/videoseries?list=PLlC7Go4yV6YKunLd6O627HTQlNswQQ6vw" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen

  h3 Wer steht hinter dieser Aktion?
  p Die Aktion wurde von Mitgliedern des Verein Legalize it! initiiert. Seit 25 Jahren helfen wir vom Verein Legalize it! Menschen, die mit THC-Produkten Umgang pflegen, bei den unterschiedlichsten Fragen.

app/views/supporters/_right_side.fr.slim
.well
  h2.sr-only A propos de l'initiative
  p = image_tag 'li_logo.svg', class: 'img-responsive', alt: 'Logo de l\'association Legalize It!'
  p Nous voulons recueillir les signatures nécessaires pour une initiative populaire pour la légalisation du cannabis. Pour l’exécution de ce projet, un nouveau concept de collection a été mis sur pieds. Cela fonctionne en trois étapes:
  
  p
    strong Etape 1:  
    | Avec ce formulaire en ligne, nous recueillions des sympathisants et des militants potentiels.
  p
    strong Etape 2:  
    | Une fois que le nombre nécessaire de personnes est atteint, nous pouvons regarder dans quel région de la Suisse se trouvent les différents militants.
  p
    strong Etape 3:  
    | Grâce à une logistique sophistiquée, les sympathisants et militants seront réunis pour pouvoir obtenir ensemble les signatures nécessaires.
  
  p.lead Donc, si tu désires <span class="text-success">légaliser le cannabis en Suisse</span>, remplis le formulaire ci-dessous et aide nous à faire un grand pas dans l'histoire
  
  h3 Qui se trouve derrière cette action?
  p L'action a été lancée par les membres de l'association Legalize It!. Depuis 25 ans, nous, de l’association Legalize It!, aidons les gens qui utilisent des produits à base de THC et répondons volontiers à leurs questions.

app/views/supporters/_right_side.it.slim
.well
  h2.sr-only A proposito l'iniziativa
  p = image_tag 'li_logo.svg', class: 'img-responsive', alt: 'Logo dell\'associazione Legalize It!'
  p Vogliamo raccogliere le firme necessarie per un'iniziativa popolare per la legalizzazione della cannabis. Per implementare l'accento su un nuovo concetto collettivo. Questo funziona in tre fasi:
  
  p
    strong Fase 1:  
    | Con questo modulo on-line che raccoglie simpatizzanti e potenziali attivisti.
  p
    strong Fase 2:  
    | Una volta raccolto il numero richiesto di persone, andiamo a vedere quante risorse di aiuto sono in nel luogo dove richiesto.
  p
    strong Fase 3:  
    | Utilizzando un sofisticata logistica riuniremo simpatizzanti e attivisti per generare congiuntamente le firme necessarie.
  
  
  p.lead Quindi, se anche tu vuoi <span class="text-success">legalizzare la Cannabis</span> in Svizzera, compila il seguente modulo e riscrivi la storia con noi.
      
  h3 Chi c’é dietro questa azione?
  p L'azione è stata sostenuta da membri dell'associazione Legalize It! Da 25 anni aiutiamo l'associazione Legalize It! Le persone che si prendono cura con prodotti THC si occupano di una vasta gamma di questioni.

app/views/supporters/new.slim
- if supporter_signed_in?
  h1.sr-only = title t('.title', name: current_supporter.first_name)
  .row
    .col-xs-12.col-md-7
      .panel.panel-default
        .panel-heading
          h2.panel-title = t '.my_data'
        .panel-body 
          dl.dl-horizontal
            dt = Supporter.human_attribute_name(:email)
            dd = current_supporter.email
            dt = Supporter.human_attribute_name(:first_name)
            dd = current_supporter.first_name
            dt = Supporter.human_attribute_name(:last_name)
            dd = current_supporter.last_name
            dt = Supporter.human_attribute_name(:street)
            dd = current_supporter.street
            dt = Supporter.human_attribute_name(:city)
            dd = "#{current_supporter.zip} #{current_supporter.city}"
            dt = Supporter.human_attribute_name(:support)
            dd == t("support_type.#{current_supporter.support}")
            dt = Supporter.human_attribute_name(:age_category)
            dd == t("age_category.#{current_supporter.age_category}")
            dt = Supporter.human_attribute_name(:language)
            dd = t("languages.#{current_supporter.language}")
            dt = Supporter.human_attribute_name(:tel)
            dd = current_supporter.tel
      
          p
            = link_to t('.edit'), edit_supporter_registration_path(), class: 'pull-right'
  
      = render 'publicity'

    aside.col-md-5.col-xs-12
      = render 'right_side'

- else
 = render 'form' 
  